config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/register" => "devise/registrations#new"
    get "/profile" => "devise/registrations#edit"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :categories do
    resources :expenses_manager, only: %i[new create edit update]
  end

  resources :expenses_manager, only: %i[index show destroy]

  root "home#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is? :admin
      can :manage, Category
      can :manage, Expense
      can :manage, User
    else
      can :manage, Category, user_id: user.id
      can :manage, Expense, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses
  has_many :expenses, through: :category_expenses

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  validates :icon, presence: true

  scope :all_categories, -> { order(created_at: :desc) }

  def display_icon
    "<i class='las la-#{icon}'></i>".html_safe
  end
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expenses
  has_many :categories, through: :category_expenses

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  validates :description, length: { minimum: 3, maximum: 400 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :ordered_expenses, -> { order(created_at: :desc) }

  def self.expenses_by_category(category_id)
    joins(:category_expenses)
      .where(category_expenses: { category_id: })
      .order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :categories
  has_many :expenses, foreign_key: 'author_id'

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, uniqueness: true

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.all.includes(:expenses)
  end

  def show
    @category = current_user.categories.includes(:expenses).find(params[:id])
    @expenses = Expense.expenses_by_category(@category.id)
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.new(category_params)
    authorize! :create, Category

    if @category.save
      flash[:notice] = "#{@category.name} was successfully created"
      redirect_to categories_path
    else
      flash[:alert] = 'The category could not be saved, please check the form and try again'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = current_user.categories.find(params[:id])
  end

  def update
    @category = current_user.categories.find(params[:id])
    authorize! :update, @category

    if @category.update(category_params)
      flash[:notice] = 'The category was successfully updated'
      redirect_to categories_path
    else
      flash[:alert] = 'The category could not be updated, please check the form and try again'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = current_user.categories.includes(:expenses).find(params[:id])
    authorize! :destroy, @category

    if @category.expenses.count.positive?
      flash[:notice] = 'The Category could not be deleted, it is already associated to some expenses.'
    else
      @category.destroy
      flash[:notice] = 'The category was successfully deleted'
    end
    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_manager_controller.rb
class ExpensesManagerController < ApplicationController
  before_action :authenticate_user!

  def index
    @expenses = current_user.expenses.ordered_expenses.includes(:categories)
  end

  def show
    @expense = current_user.expenses.includes(:categories).find(params[:id])
  end

  def new
    @category = current_user.categories.find(params[:category_id])
    @expense = current_user.expenses.new
  end

  def create
    @category = current_user.categories.find(params[:category_id])
    @expense = current_user.expenses.new(expenses_params)
    authorize! :create, Expense

    if @expense.save
      CategoryExpense.create(category_id: @category.id, expense_id: @expense.id)
      if params[:categories].present?
        params[:categories].each do |category|
          if CategoryExpense.find_by(category_id: category, expense_id: @expense.id).nil?
            CategoryExpense.create(category_id: category, expense_id: @expense.id)
          end
        end
      end
      flash[:notice] = "#{@expense.name} was successfully created"
      redirect_to category_path(@category)
    else
      flash[:alert] = 'The expense could not be saved, please check the form and try again'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = current_user.categories.find(params[:category_id])
    @expense = current_user.expenses.find(params[:id])
  end

  def update
    @category = current_user.categories.find(params[:category_id])
    @expense = current_user.expenses.find(params[:id])
    authorize! :create, Expense

    if @expense.update(expenses_params)
      @expense.category_expenses.destroy_all
      CategoryExpense.create(category_id: @category.id, expense_id: @expense.id)
      if params[:categories].present?
        params[:categories].each do |category|
          if CategoryExpense.find_by(category_id: category, expense_id: @expense.id).nil?
            CategoryExpense.create(category_id: category, expense_id: @expense.id)
          end
        end
      end
      flash[:notice] = "#{@expense.name} was successfully updated"
      redirect_to category_path(@category)
    else
      flash[:alert] = 'The expense could not be saved, please check the form and try again'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @expense = current_user.expenses.includes(:category_expenses).find(params[:id])
    authorize! :destroy, @expense

    @expense.category_expenses.destroy_all
    @expense.destroy
    flash[:notice] = 'The expense was successfully deleted'

    redirect_to expenses_manager_path, status: :see_other
  end

  private

  def expenses_params
    params.require(:expense).permit(:name, :amount, :description, :photo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless current_user

    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def back_button(url, icon_class = 'las la-arrow-left')
    link_to raw("<i class='#{icon_class}'></i>"), url, class: 'clear-button icon-button'
  end

  def right_button(url, icon_class = 'las la-arrow-left')
    link_to raw("<i class='#{icon_class}'></i>"), url, class: 'clear-button icon-button'
  end

  def right_submit_button(form, submit_text)
    form.submit submit_text, class: 'clear-button'
  end

  def menu_button
    '<button id="toggleSidebar" class="menu-button"><i class="las la-bars"></i></button>'.html_safe
  end

  def line_awesome_icons
    %w[home arrow-left heart wallet pen book building flower]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_category.html.erb
<div class="category-thumb">
    <div class="icon-div">
        <%= category.display_icon %>
    </div>
    <div class="text-div">
        <h3><%= link_to category.name, category %></h3>
        <small><%= category.created_at.strftime("%B %d, %Y") %></small>
        <div class="actions">
            <%= link_to raw("<i class='las la-pen primary-text'></i>"), edit_category_path(category), class: 'clear-button icon-button' if can? :update, category %>
            <%= link_to raw("<i class='las la-trash danger-text'></i>"), category_path(category), data: {
                    turbo_method: :delete,
                    turbo_confirm: 'Are you sure you want to delete this category?'
                }, class: 'clear-button icon-button' if can? :destroy, category %>
        </div>
    </div>
    <div class="stats-div">
        <span>$<%= category.expenses.sum {|expense| expense.amount} %></span>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div id="selected-icon" class="choosen-icon">
    <%= category.display_icon if category.icon %>
  </div>
  <div class="field">
    <%= form.label :icon %><br>
    <%= form.select :icon, line_awesome_icons, {}, { id: 'icon-select', prompt: 'Select an icon', 'data-turbo-frame': 'false' } %>
    <% category.errors.full_messages_for(:icon).each do |message| %>
      <p class='error-messages'><%= message %></p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, placehoder: 'category' %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <p class='error-messages'><%= message %></p>
    <% end %>
  </div>

  <div class="submit-button">
    <%= form.submit "Save", class: 'primary-button' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "category" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'Edit category', from_form: false, next_path: categories_path, next_text: nil } %>

<div class="category-form">
    <%= render 'form', category: @category %>
</div>

app/views/categories/index.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "category" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'categories', from_form: false, next_path: categories_path, next_text: 'search' } %>

<div class="categories">
    <% if @categories.count > 0 %>
        <% @categories.each do |category| %>
            <%= render category %>
        <% end %>
    <% else %>
        <small> No categories added, <%= link_to "click", new_category_path, class: 'clear-button' %> to add.</small>
    <% end %>
</div>

<%= link_to raw("<span>Add new category</span>"), new_category_path, class: 'secondary-button floating-button' if can? :create, Category %>

app/views/categories/new.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "category" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'new category', from_form: false, next_path: categories_path, next_text: 'search' } %>

<div class="category-form">
    <%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "category" %>
<%= stylesheet_link_tag "expense" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'expenses', from_form: false, next_path: categories_path, next_text: 'search' } %>

<div class="expense-header">
    <span><%= @category.name %></span>
    <span class="total">$<%= @category.expenses.sum {|expense| expense.amount} %></span>
</div>

<div class="expenses">
    <% if @expenses.count > 0 %>
        <% @expenses.each do |expense| %>
            <%= render 'expenses_manager/expense', {category: @category, expense: expense} %>
        <% end %>
    <% else %>
        <small> No expense added for this category, <%= link_to "click", new_category_expenses_manager_path(@category), class: 'clear-button' %> to add.</small>
    <% end %>
</div>

<%= link_to raw("<span>Add new expense</span>"), new_category_expenses_manager_path(@category), class: 'secondary-button floating-button' if can? :create, Category %>

app/views/expenses_manager/_expense.html.erb
<div class="expense-thumb">
    <div class="image-div">
        <%= image_tag expense.photo.url, id: "imagePreview" if expense.photo.present? %>
        <%= image_tag('wallet.png', id: "imagePreview") unless expense.photo.present? %>
    </div>
    <div class="text-div">
        <h3><%= link_to expense.name, expenses_manager_path(expense) %></h3>
        <p><%= truncate(expense.description, length: 20) %>...</p>
        <p>
            <% expense.categories.each do |cat|  %>
                <%= link_to cat.name, category_path(category), class: 'clear-button tags' %>
            <% end %>
        </p>
        <small><%= expense.created_at.strftime("%B %d, %Y") %></small>
        <div class="actions">
            <%= link_to raw("<i class='las la-pen primary-text'></i>"), edit_category_expenses_manager_path(category, expense), class: 'clear-button icon-button' if can? :update, expense %>
            <%= link_to raw("<i class='las la-trash danger-text'></i>"), expenses_manager_path(expense), data: {
                    turbo_method: :delete,
                    turbo_confirm: 'Are you sure you want to delete this category?'
                }, class: 'clear-button icon-button' if can? :destroy, expense %>
        </div>
    </div>
    <div class="stats-div">
        <span>$<%= expense.amount %></span>
    </div>
</div>

app/views/expenses_manager/_form.html.erb
<%= form_with model: [category, expense], url: submit_path do |form| %>
    <div class="field photo-upload">
      <div class="photo-view">
        <%= image_tag expense.photo.url, id: "imagePreview" if expense.photo.present? %>
        <%= image_tag('wallet.png', id: "imagePreview") unless expense.photo.present? %>
      </div>

      <label class="custom-file-upload">
          <%= form.file_field :photo, id: "user_photo", accept: 'image/*', onchange: 'previewImage(event)' %>
          upload picture
      </label>
    </div>
  
  <div class="field">
    <% current_user.categories.where.not(id: @category.id).each do |category| %>
      <%= check_box_tag 'categories[]', category.id, @expense.categories.include?(category) %>
      <%= label_tag "categories_#{category.id}", category.name %><br>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, placehoder: 'Name' %>
    <% expense.errors.full_messages_for(:name).each do |message| %>
      <p class='error-messages'><%= message %></p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :amount %><br>
    <%= form.number_field :amount, placehoder: 'Amount' %>
    <% expense.errors.full_messages_for(:amount).each do |message| %>
      <p class='error-messages'><%= message %></p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, placehoder: 'Description' %>
    <% expense.errors.full_messages_for(:description).each do |message| %>
      <p class='error-messages'><%= message %></p>
    <% end %>
  </div>

  <div class="submit-button">
    <%= form.submit "Save", class: 'primary-button' %>
  </div>
<% end %>

app/views/expenses_manager/edit.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "expense" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'edit expense', from_form: false, next_path: categories_path, next_text: nil } %>

<div class="expense-form">
    <%= render 'form', {category: @category, expense: @expense, submit_path: category_expenses_manager_path(@category, @expense)} %>
</div>

app/views/expenses_manager/index.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "expense" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'all expenses', from_form: false, next_path: categories_path, next_text: 'search' } %>

<div class="expenses">
    <% if @expenses.count > 0 %>
        <% @expenses.each do |expense| %>
            <%= render 'expense', {category: expense.categories.first, expense: expense} %>
        <% end %>
    <% else %>
        <small> No expense added .</small>
    <% end %>
</div>

app/views/expenses_manager/new.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "expense" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'new expense', from_form: false, next_path: category_path(@category), next_text: 'search' } %>

<div class="expense-form">
    <%= render 'form', {category: @category, expense: @expense, submit_path: category_expenses_manager_index_path(@category, @expense)} %>
</div>

app/views/expenses_manager/show.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "category" %>
<%= stylesheet_link_tag "expense" %>

<%= render "layouts/nav_bar", {prev_path: nil, title: 'expense ' + @expense.name, from_form: false, next_path: categories_path, next_text: 'search' } %>

<div class="expense-header">
    <span><%= @expense.name %></span>
    <span class="total">$<%= @expense.amount %></span>
</div>
<div class="expenses">
    <p><%= @expense.description %></p>
</p>

app/views/home/index.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "home" %>

<div class="splashscreen">
    <div class="logo">
        <%= image_tag('animated-logo.gif') %>
    </div>
    <div class="buttons">
        <%= link_to "log in", login_path , class: 'primary-button' %>
        <%= link_to "sign up", register_path , class: 'clear-button' %>
    </div>
</div>

app/views/layouts/_nav_bar.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "side_bar" %>

<div class="nav-bar" id="navbar">
    <% if prev_path %>
        <%= back_button(prev_path) %>
    <% else %>
        <%= menu_button %>
    <% end %>
    <span><%= title %></span>
    <% if from_form %>
        <%= right_submit_button(form, submit_text) %>
    <% else %>
        <%= right_button(next_path) %>
    <% end %>
</div>

app/views/layouts/_side_bar.html.erb
<div id="sidebar">
    <div class="avatar-div">
        <%= image_tag current_user.photo.url if current_user.photo.present? %>
        <%= image_tag('default-avatar.png') unless current_user.photo.present? %>
        <span><%= current_user.name %>
    </div>
    <div class="menu-div">
        <%= link_to raw("<i class='las la-layer-group'></i> <span>Categories</span>"), categories_path %>
        <%= link_to raw("<i class='las la-wallet'></i> <span>Expenses</span>"), expenses_manager_index_path %>
        <%= link_to raw("<i class='las la-user'></i> <span>Profile</span>"), profile_path %>
        <%= link_to raw("<i class='las la-sign-out-alt'></i> <span>Logout</span>"), logout_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpensesController</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="flash <%= type %>">
        <%= message %>
      </div>
    <% end %>
    <%= render 'layouts/side_bar' if current_user %>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>